wxFreeChart: Dataset Class Reference
Dataset Class Reference
#include <dataset.h>
Public Member Functions
void SetRenderer (Renderer *renderer)
Renderer * GetBaseRenderer ()
void BeginUpdate ()
void EndUpdate ()
virtual size_t GetSerieCount ()=0
virtual size_t GetCount (size_t serie)=0
virtual wxString GetSerieName (size_t serie)=0
virtual double GetMinValue (bool vertical)=0
virtual double GetMaxValue (bool vertical)=0
virtual DateTimeDataset * AsDateTimeDataset ()
void AddMarker (Marker *marker)
size_t GetMarkersCount ()
Marker * GetMarker (size_t index)
virtual void NeedRedraw (DrawObject *obj)
Protected Member Functions
virtual bool AcceptRenderer (Renderer *r)=0
void DatasetChanged ()
Protected Attributes
Renderer * m_renderer
Detailed Description
Base class for all datasets (XYDatasets, XYZDatasets, CategoryDatasets, OHLCDatasets, etc).
Member Function Documentation
virtual bool Dataset::AcceptRenderer (Renderer * r) [protected, pure virtual]
Checks whether renderer is acceptable by this dataset. TODO: this method must be removed, because acceptable renderer type depends on plot type.
Implemented in CategoryDataset, OHLCDataset, and XYDataset.
void Dataset::AddMarker (Marker * marker)
Adds marker to plot. Plot takes ownership of marker.
Parameters:
marker marker to be added
void Dataset::BeginUpdate ()
Called to begin dataset update. Each call must have corresponding EndUpdate call. Increment dataset update counter.
void Dataset::DatasetChanged () [protected]
Called to indicate, that dataset is changed. For call by derivate classes.
Referenced by VectorDataset::Add(), VectorDataset::Clear(), VectorDataset::RemoveAt(), VectorDataset::Replace(), and OHLCDataset::SetSerieName().
void Dataset::EndUpdate ()
Called to end dataset update. Decrement dataset update counter, and fires DatasetChanged event when counter equal zero.
virtual size_t Dataset::GetCount (size_t serie) [pure virtual]
Returns value count in serie specified by index.
Parameters:
serie index
Returns:
value count
Implemented in CategoryDataset, GanttDataset, OHLCDataset, Polynom, SineFunction, VectorDataset, XYDynamicDataset, and XYSimpleDataset.
Marker* Dataset::GetMarker (size_t index)
Returns marker at specified index.
Parameters:
index index of marker
Returns:
marker at specified index
size_t Dataset::GetMarkersCount ()
Returns marker count.
Returns:
marker count
virtual double Dataset::GetMaxValue (bool vertical) [pure virtual]
Returns maximal value.
Parameters:
vertical for datasets with XY coordinates, specifies direction
Returns:
maximal value
Implemented in CategoryDataset, OHLCDataset, and XYDataset.
virtual double Dataset::GetMinValue (bool vertical) [pure virtual]
Returns minimal value.
Parameters:
vertical for datasets with XY coordinates, specifies direction
Returns:
minimal value
Implemented in CategoryDataset, OHLCDataset, and XYDataset.
virtual size_t Dataset::GetSerieCount () [pure virtual]
Returns serie count in this dataset.
Returns:
serie count
Implemented in CategorySimpleDataset, GanttSimpleDataset, OHLCDataset, Polynom, SineFunction, VectorDataset, XYDynamicDataset, and XYSimpleDataset.
virtual wxString Dataset::GetSerieName (size_t serie) [pure virtual]
Returns serie name.
Parameters:
serie index
Returns:
serie name
Implemented in CategorySimpleDataset, GanttSimpleDataset, OHLCDataset, Polynom, SineFunction, VectorDataset, XYDynamicDataset, and XYSimpleDataset.
void Dataset::SetRenderer (Renderer * renderer)
Sets renderer for this dataset.
Parameters:
renderer new renderer
The documentation for this class was generated from the following file:
include/wx/dataset.h