wxFreeChart: AxisObserver Class Reference
AxisObserver Class Reference abstract
#include <axis.h>
Public Member Functions
virtual void AxisChanged (Axis *axis)=0
virtual void BoundsChanged (Axis *axis)=0
Detailed Description
Interface to receive axis events.
Member Function Documentation
virtual void AxisObserver::AxisChanged (Axis * axis) pure virtual
Called when axis is changed.
Parameters
axis changed axis
Implemented in AxisPlot, and Chart.
Referenced by AxisPlot::GetAxisDataset(), and Chart::SetTitle().
virtual void AxisObserver::BoundsChanged (Axis * axis) pure virtual
Called when axis bounds are changed.
Parameters
axis axis that bounds are changed
Implemented in AxisPlot, and Chart.
Referenced by AxisPlot::GetAxisDataset(), and Chart::SetTitle().
The documentation for this class was generated from the following file:
include/wx/axis/axis.h