wxFreeChart: MultiPlot Class Reference
MultiPlot Class Reference
#include <multiplot.h>
Public Member Functions
MultiPlot (int rows, int cols, wxCoord horizGap, wxCoord vertGap)
void AddPlot (Plot *subPlot)
virtual void PlotNeedRedraw (Plot *plot)
Public Member Functions inherited from Plot
virtual void Draw (wxDC &dc, wxRect rc)
virtual void DrawNoDataMessage (wxDC &dc, wxRect rc)
void SetChartPanel (wxChartPanel *chartPanel)
wxChartPanel * GetChartPanel ()
void SetBackground (AreaDraw *background)
void SetTextNoData (const wxString &textNoData)
Public Member Functions inherited from Observable< PlotObserver >
void AddObserver (PlotObserver *_observer)
void RemoveObserver (PlotObserver *_observer)
Protected Member Functions
virtual bool HasData ()
virtual void DrawData (wxDC &dc, wxRect rc)
Protected Member Functions inherited from Plot
virtual void DrawDataAreaBackground (wxDC &dc, wxRect rc)
virtual void ChartPanelChanged (wxChartPanel *oldPanel, wxChartPanel *newPanel)
FIRE_WITH_THIS (PlotNeedRedraw)
Additional Inherited Members
Public Types inherited from Observable< PlotObserver >
typedef PlotObserver Observer
Public Attributes inherited from Observable< PlotObserver >
std::vector< PlotObserver * >::iterator OIt
Protected Attributes inherited from Observable< PlotObserver >
std::vector< PlotObserver * > observers
Detailed Description
Multiplot is plot containing one or more plots, called subplots. It arranges subplots to rows and columns.
Constructor & Destructor Documentation
MultiPlot::MultiPlot (int rows, int cols, wxCoord horizGap, wxCoord vertGap)
Constructs new multiplot.
Parameters
rows number of rows for subplots
cols number of columns for subplots
horizGap distance between columns
vertGap distance between rows
Member Function Documentation
void MultiPlot::AddPlot (Plot * subPlot) inline
Add plot to this multiplot.
Parameters
subPlot plot to be added
References Plot::DrawData(), Plot::HasData(), and PlotObserver::PlotNeedRedraw().
virtual void MultiPlot::DrawData (wxDC & dc, wxRect rc) protected virtual
Draw the plot data, i.e. the lines, bars etc. on top of the background. Must be overriden by derivative classes.
Parameters
dc device context
rc rectangle where to draw
Implements Plot.
virtual bool MultiPlot::HasData () protected virtual
Checks whether plot has data. Must be overriden by derivative classes.
Returns
true if plot has data, false overwise
Implements Plot.
virtual void MultiPlot::PlotNeedRedraw (Plot * _plot) virtual
Called when plot has been changed and need to be redrawn.
Parameters
_plot plot
Implements PlotObserver.
The documentation for this class was generated from the following file:
include/wx/multiplot.h